"""
This is a setup.py script generated by py2applet

Usage: python setup.py py2app
"""

from setuptools import setup

APP = ['detection.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True, 'includes': ['PyQt5'],
           'plist': {'CFBundleShortVersionString':'0.1.0',},
           'iconfile':'icon.icns'}

setup(name='Detection',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
